### ISSUE TITLE
Uso do interpretador

### ISSUE THREAD

**Issue by GiulianoWF** [cimtools/aclc#1]
Eu sou um bolsista trabalho no LabCim.
Estamos desenvolvendo um novo software pra substituir o RoboSoft. Para isso seria conveniente usar o presente interpretador de ACL para verificar erro de sintaxe em programas escritos.
Estamos com um pouco de dificuldade devido ao fato do interpretador, quando fazendo a interpretação, solicita entradas do usuário. 
Precisaríamos executa-lo apenas para checar possíveis erros de sintaxe. Isso sería possível? 
Caso contrário indicaría alguma outra solução?
Grato desde já.

**Comment by filipi** [comment]
Olá Giuliano,
O interpretador converte o código acl para perl e executa o código perl.
Ele não faz verificação de sintaxe.

Talvez possamos adicionar um "command line switch" para desabilitar a entrada de dados pelo usuário... Que tal?

**Comment by GiulianoWF** [comment]
Boa tarde, 
Nesse caso iremos procurar por mais alternativas para checagem de sintaxe. Talvez no código antigo encontremos algo.
Grato pela atenção.
